
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Network URL: http://169.255.254.1:8503
  External URL: http://54.83.37.5:8503

2024-05-14 20:38:21.916 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/sagemaker-user/newDEMO/app-kb.py", line 226, in <module>
    st.text_area(f"Q:", value = user_input)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 397, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 496, in text_area
    return self._text_area(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 580, in _text_area
    widget_state = register_widget(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 164, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 209, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple identical `st.text_area` widgets with the
same generated key.

When a widget is created, it's assigned an internal key based on
its structure. Multiple widgets with an identical structure will
result in the same internal key, which causes this error.

To fix this error, please pass a unique `key` argument to
`st.text_area`.
2024-05-14 20:45:07.969 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/sagemaker-user/newDEMO/app-kb.py", line 233, in <module>
    st.text_area(f"Q:", value = prompt)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 397, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 496, in text_area
    return self._text_area(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 580, in _text_area
    widget_state = register_widget(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 164, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 209, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple identical `st.text_area` widgets with the
same generated key.

When a widget is created, it's assigned an internal key based on
its structure. Multiple widgets with an identical structure will
result in the same internal key, which causes this error.

To fix this error, please pass a unique `key` argument to
`st.text_area`.
2024-05-14 20:45:40.339 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/sagemaker-user/newDEMO/app-kb.py", line 233, in <module>
    st.text_area(f"Q:", value = user_input)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 397, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 496, in text_area
    return self._text_area(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 580, in _text_area
    widget_state = register_widget(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 164, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 209, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple identical `st.text_area` widgets with the
same generated key.

When a widget is created, it's assigned an internal key based on
its structure. Multiple widgets with an identical structure will
result in the same internal key, which causes this error.

To fix this error, please pass a unique `key` argument to
`st.text_area`.
2024-05-14 20:46:40.153 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/sagemaker-user/newDEMO/app-kb.py", line 233, in <module>
    st.text_area(f"Q:", value = user_input)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 397, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 496, in text_area
    return self._text_area(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 580, in _text_area
    widget_state = register_widget(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 164, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 209, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple identical `st.text_area` widgets with the
same generated key.

When a widget is created, it's assigned an internal key based on
its structure. Multiple widgets with an identical structure will
result in the same internal key, which causes this error.

To fix this error, please pass a unique `key` argument to
`st.text_area`.
2024-05-14 20:47:10.648 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/sagemaker-user/newDEMO/app-kb.py", line 233, in <module>
    st.text_area(f"Q:", value = user_input)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 397, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 496, in text_area
    return self._text_area(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/elements/widgets/text_widgets.py", line 580, in _text_area
    widget_state = register_widget(
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 164, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)
  File "/opt/conda/lib/python3.9/site-packages/streamlit/runtime/state/widgets.py", line 209, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple identical `st.text_area` widgets with the
same generated key.

When a widget is created, it's assigned an internal key based on
its structure. Multiple widgets with an identical structure will
result in the same internal key, which causes this error.

To fix this error, please pass a unique `key` argument to
`st.text_area`.
